name: copy_readme

on:
  push:
    branches-ignore: [master, main]
jobs:
  copy_readme:
    runs-on: ubuntu-latest
    steps:
      - id: s1
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: s2
        name: Copy README
        run: |
          cp ./README.md ./profile/README.md
      - id: s3
        name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [[ $(git diff --name-only --cached | wc -l) -ne 0 ]]; then
            git add -A
            git commit -m "copied readme to /profile"
            exit 0
          else
            exit 1
          fi
      - id: s4
        name: Push changes
        if: steps.s3.conclusion == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
